/*
  Metadata é utilizada pelo Next.js
  para definir informações da página,
  como título e descrição.
*/
import type { Metadata } from "next";

/*
  Importa fontes disponibilizadas
  pelo próprio Next.js.
*/
import { Geist, Geist_Mono } from "next/font/google";

/*
  Importa o arquivo de estilos globais
  utilizado por toda a aplicação.
*/
import "./globals.css";


/*
  Configuração da fonte Geist Sans.

  A variável criada pode ser utilizada
  nos estilos da aplicação.
*/
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


/*
  Configuração da fonte Geist Mono.
*/
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


/*
  METADATA

  Define informações gerais da aplicação
  que podem aparecer no navegador
  e serem utilizadas pelo Next.js.
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/*
  ROOT LAYOUT

  Este é o layout principal da aplicação.

  Ele envolve TODAS as páginas do projeto,
  inclusive páginas como login e páginas
  internas do sistema.

  Os layouts internos, como o SistemaLayout,
  são adicionados dentro deste layout principal.
*/
export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    /*
      Define a estrutura HTML principal
      da aplicação.

      lang="pt-BR" informa que o idioma
      principal da página é português do Brasil.
    */
    <html
      lang="pt-BR"
      className="h-full"
    >

      {/*
        children representa todo o conteúdo
        da rota acessada.

        Dependendo da página,
        esse conteúdo também pode passar
        por outros layouts internos.
      */}
      <body>
        {children}
      </body>

    </html>
  );
}